# Dockerfile.test

# Using the current latest stable slim version of Python on the stable version of Debian explicitly
FROM python:3.13.0-slim-bookworm

# set the app directory
WORKDIR /test_app

# copy the requirements file to the workdir
COPY requirements.txt .
# copy the test script to the workdir
COPY test.py .
# copy the expected html to check against
COPY expected.html .

# pip install requirements
RUN pip install -r requirements.txt

CMD ["python", "test.py"]