name: 'nginx_fam'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "${HTML_PORT}:8080"
      - "${ERROR_PORT}:8081"
    networks:
      - test-network
  test:
    build:
      context: ./test
      dockerfile: Dockerfile.test
    networks:
      - test-network
    depends_on:
      - nginx
    volumes:
      - ./result:/result # bind the container result dir to the host for github actions check

networks:
  test-network:
    driver: bridge # only allow connections between containers and not the host