name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual triggering for the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: build images
      run: docker compose build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: run docker compose
      run: docker compose up -d # run the docker images in the background

    - name: wait for test result
      run: |
        while [ ! -f ./result/succeeded ] && [ ! -f ./result/fail ]; do
          echo "waiting for test results..."
          sleep 1
        done

    - name: upload test result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-result
        path: |
          ./result/succeeded
          ./result/fail