name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual triggering for the workflow

env:
  # define the different host ports in a single place for configuration
  HTML_PORT: 8081
  ERROR_PORT: 8082

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: build images
      run: docker compose build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: run docker compose
      run: docker compose up -d # run the docker images in the background

    - name: wait for test result
      run: |
        max_attempts=10
        for ((i=1; i<=max_attempts; i++)); do
          if [ -f ./result/succeeded ] || [ -f ./result/fail ]; then
            echo "Test result found."
            break
          fi
          echo "Waiting for test results... ($i seconds elapsed)"
          sleep 1
        done
          if [ $i -ge 10 ]; then
            echo "Timeout reached while waiting for test results."
            exit 1  # Exit with failure
          fi

    - name: upload test result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-result
        path: |
          ./result/succeeded
          ./result/fail